# Generated by Django 4.0 on 2022-01-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0002_comentario_publicacion_alter_publicacion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='publicacion',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
